#该工作流将构建一个节点.js应用程序，并在将提交推送到默认分支时将其推送到Azure Web App。
#
#此工作流假定您已经创建了目标Azure应用服务Web应用。
#有关说明，请参阅https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
#配置此工作流：
#
#1。下载Azure Web应用程式的发布配置文件。您可以从Azure门户网站中Web App的“概述”页下载此文件。
#有关详细信息：https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
#2.在存储库中创建名为Azure_webapp_PUBLISH_PROFILE的密码，将发布配置文件内容粘贴为密码的值。
#有关获取发布配置文件的说明，请参阅：https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-Github-secret
#
#3.更改Azure_webapp_NAME的值。(可选)更改下面的Azure_webapp_PACKAGE_PATH和node_VERSION环境变量。
#
#有关Azure的GitHub操作的详细信息：https://github.com/Azure/Actions
#有关Azure Web应用程序部署操作的详细信息：https://github.com/Azure/webapps-deploy
#要获得更多示例，以开始使用要部署到Azure的GitHub操作工作流：https://github.com/Azure/actions-workflow-samples

在……之上:
推:
分支机构: [ "SukiSU-Ultra" ]
workflow_dispatch:

env:
Azure_webapp_NAME: 您的应用程序名称#将此设置为应用程序的名称
Azure_webapp_PACKAGE_PATH: '.'      #将此设置为Web应用程序项目的路径，默认设置为存储库根目录
node_VERSION: '20.x'                #将此设置为要使用的节点版本

权限:
内容: 读

工作:
建立:
连续的: Ubuntu-最新
步骤:
-使用：操作/结帐@v4uses: 操作/结帐@v4

-名称：设置Node.jsname: 设置Node.js
用途：操作/setup-node@v4: 操作/设置-节点@v4
和……一起:
节点版本：${{env.NODE_VERSION}}: ${{env.NODE_VERSION}}
缓存: 'npm'

-名称：npm安装、构建和测试name: npm安装、构建和测试
跑: |
npm安装
npm运行内部版本--if-resent
npm运行测试--如果存在

-名称：为部署作业上载对象name: 为部署作业上载项目
用法：操作/上载工件@v4: 操作/上载工件@v4
和……一起:
名称：node-app: node-app
路径: .

部署:
权限:
内容：无: 没有一个
run-on:ubuntu-latest: Ubuntu-最新
需求：构建: 建立
环境:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
